### ISSUE TITLE
zombie child processes

### ISSUE THREAD

**Issue by sibrat** [droberson/ssh-honeypot#1]
Zombie created with each authentication request.
i think something like this http://stackoverflow.com/questions/17015830/how-can-i-prevent-zombie-child-processes can help you solve problem

**Comment by droberson** [comment]
Should be fixed now. I simply ignored SIGCHLD signals. Thank you for pointing this out!

**Comment by sibrat** [comment]
nope. I still getting horde of zombies :)

**Comment by droberson** [comment]
on version 0.0.3? what type of system are you running this on? I confirmed the bug in 0.0.2, applied the fix, and it is no longer leaving zombies hanging on 0.0.3

**Comment by sibrat** [comment]
CentOs 3.10.0-514.2.2.el7.x86_64. Oh, i see problem: you add code in "if (daemonize == 1) {}
". But i don't daemonize it :)

**Comment by droberson** [comment]
Doh! Should be good now.
