### ISSUE TITLE
FATAL: ssh_bind_listen(): 

### ISSUE THREAD

**Issue by s0i37** [droberson/ssh-honeypot#12]
```
~/src/ssh-honeypot(master) » sudo bin/ssh-honeypot -p 22 -u nobody                                          
[Tue May 19 14:50:10 2020] ssh-honeypot 0.1.0 by Daniel Roberson started on port 22. PID 1073190
[Tue May 19 14:50:10 2020] FATAL: ssh_bind_listen(): 
--------------------------------------------------------------------------------------------------------------------------------
~/src/ssh-honeypot(master) » sudo bin/ssh-honeypot -p 2222 -u nobody                                        
[Tue May 19 14:50:13 2020] ssh-honeypot 0.1.0 by Daniel Roberson started on port 2222. PID 1073210
[Tue May 19 14:50:13 2020] FATAL: ssh_bind_listen(): 
--------------------------------------------------------------------------------------------------------------------------------
~/src/ssh-honeypot(master) » sudo bin/ssh-honeypot -p 22222 -u nobody                                       
[Tue May 19 14:50:16 2020] ssh-honeypot 0.1.0 by Daniel Roberson started on port 22222. PID 1073226
[Tue May 19 14:50:16 2020] FATAL: ssh_bind_listen(): 
```

**Comment by link89** [comment]
`-r` option is required. Check the readme file.

**Comment by pandalatte** [comment]
Same thing is happening to me.

root@ubuntu:~/tools/ssh-honeypot# ls -la ssh-honeypot.*
-rw------- 1 root root 2655 Sep 29 17:58 ssh-honeypot.rsa
-rw-r--r-- 1 root root  565 Sep 29 17:58 ssh-honeypot.rsa.pub
root@ubuntu:~/tools/ssh-honeypot# bin/ssh-honeypot -r ./ssh-honeypot.rsa -p 22 -v            
[Tue Sep 29 18:09:41 2020] ssh-honeypot 0.1.0 by Daniel Roberson started on port 22. PID 295712
[Tue Sep 29 18:09:41 2020] FATAL: ssh_bind_listen(): 

root@ubuntu:~/tools/ssh-honeypot# bin/ssh-honeypot -r ./ssh-honeypot.rsa -p 2222 -v
[Tue Sep 29 18:09:47 2020] ssh-honeypot 0.1.0 by Daniel Roberson started on port 2222. PID 295715
[Tue Sep 29 18:09:47 2020] FATAL: ssh_bind_listen(): 

root@ubuntu:~/tools/ssh-honeypot# bin/ssh-honeypot -r ./ssh-honeypot.rsa -p 22222 -v
[Tue Sep 29 18:09:50 2020] ssh-honeypot 0.1.0 by Daniel Roberson started on port 22222. PID 295718
[Tue Sep 29 18:09:50 2020] FATAL: ssh_bind_listen():

**Comment by RiversideRocks** [comment]
Getting the same error here.

**Comment by SuperSchelli** [comment]
happens to me as well, i am using -r option and it still happens

**Comment by s0i37** [comment]
Indeed:
```
ssh-keygen -t rsa -f ./ssh-honeypot.rsa
./bin/ssh-honeypot -r ssh-honeypot.rsa -p 2222
```
It works! 👍

**Comment by DmitroC** [comment]
U need to be root). Ports behind 1024 is needed to be launched from root.
