### ISSUE TITLE
Clang needed

### ISSUE THREAD

**Issue by myxxmikeyxx** [droberson/ssh-honeypot#22]
Should I install build essentials or just install clang?
I am using Ubuntu 20.04 server so it does not have anything, and I would like to keep it as lightweight as possible.

**Comment by droberson** [comment]
Removed the hard-coded CC=clang in the Makefile. This should work fine with gcc.

**Comment by droberson** [comment]
Removed hard-coded clang in Makefile.

**Comment by myxxmikeyxx** [comment]
Thank you I will have to try that.
