### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 0xman** [droberson/ssh-honeypot#5]
How do i make it only log the username/passwords? And not the timestamps or ips?

**Comment by droberson** [comment]
edit log_entry() and handle_ssh_auth() to taste, then recompile.

**Comment by 0xman** [comment]
LOL are you messing with me ?

**Comment by droberson** [comment]
no.

**Comment by 0xman** [comment]
lol editing log_entry() and handle_ssh_auth() to taste does nothing

**Comment by droberson** [comment]
perhaps we aren't understanding each other. if you want to alter the way the program logs data, that's what you'd need to edit.

**Comment by 0xman** [comment]
Yes i wanted to alter the way the program logs data just to log username and password

**Comment by droberson** [comment]
then you would need to edit those two functions to however you want it to log. you can do it. i believe in you.

**Comment by fanzhuyifan** [comment]
> Yes i wanted to alter the way the program logs data just to log username and password

I mean, if you don't want to mess with the code, you can also use a quick awk to select only the username and password and output to another file.

**Comment by 0xman** [comment]
> > Yes i wanted to alter the way the program logs data just to log username and password
> 
> I mean, if you don't want to mess with the code, you can also use a quick awk to select only the username and password and output to another file.

could you send me to command line to use awk  to output username & password into another file?

**Comment by 0xman** [comment]
Never mind i used my brain and found out how to use awk lol
