### ISSUE TITLE
[feature] allow disabling the file log

### ISSUE THREAD

**Issue by tedder** [droberson/ssh-honeypot#8]
I _think_ I can run ssh-honeypot on a readonly filesystem if it didn't need to log. As a workaround, I'm logging to `/dev/null` right now, but with the way `log_entry()` is written, writing to console or syslog is _in addition to_ the logfile, which is unfortunate.

**Comment by droberson** [comment]
Added -L flag to toggle writing to a file; https://github.com/droberson/ssh-honeypot/commit/10a6caf7c087b64981d88226018366fe20dd0e1d
